package mtsafety.cli;

import java.util.List;

import mt.safety.scanner.core.CodePatterns;
import mt.safety.scanner.core.Indicator;
import mt.safety.scanner.core.PairIndicator;

/**
 * Prints the pattern catalogue as Markdown.
 *
 * <p>The rule reference in {@code docs/} is generated by this rather than written by hand, so it
 * cannot drift away from the rules that actually run. Regenerate with {@code tools/build.sh docs}.
 */
public final class RuleCatalogDoc {

    public static void main(String[] args) {
        System.out.println("| Rule | Severity | Category | What it means |");
        System.out.println("| --- | --- | --- | --- |");
        List<Indicator> indicators = CodePatterns.indicators();
        for (int i = 0; i < indicators.size(); i++) {
            Indicator indicator = indicators.get(i);
            System.out.println("| `" + indicator.ruleId + "` | " + indicator.severity.label() + " | "
                    + indicator.category.label() + " | **" + indicator.title + ".** "
                    + indicator.detail + " |");
        }
        System.out.println();
        System.out.println("### Same-file combinations");
        System.out.println();
        System.out.println("| Rule | Severity | Category | What it means |");
        System.out.println("| --- | --- | --- | --- |");
        List<PairIndicator> pairs = CodePatterns.pairs();
        for (int i = 0; i < pairs.size(); i++) {
            PairIndicator pair = pairs.get(i);
            System.out.println("| `" + pair.ruleId + "` | " + pair.severity.label() + " | "
                    + pair.category.label() + " | **" + pair.title + ".** " + pair.detail + " |");
        }
    }

    private RuleCatalogDoc() {
    }
}
